admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

tn_t:
    resource: "@TrackBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path:    /logout